"""empty message

Revision ID: ae4a3faba3e5
Revises: f599e59038fd
Create Date: 2021-06-17 22:02:01.061722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae4a3faba3e5'
down_revision = 'f599e59038fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('categories', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'store', 'category', ['categories'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'store', type_='foreignkey')
    op.drop_column('store', 'categories')
    # ### end Alembic commands ###
