"""empty message

Revision ID: b5e3ea3739c7
Revises: bf26eb7fdc8f
Create Date: 2021-06-17 21:12:33.767255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5e3ea3739c7'
down_revision = 'bf26eb7fdc8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('categories_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'category', ['categories_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'categories_id')
    # ### end Alembic commands ###
