"""empty message

Revision ID: bf26eb7fdc8f
Revises: 2d9afc7f3b40
Create Date: 2021-06-17 17:49:51.093815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf26eb7fdc8f'
down_revision = '2d9afc7f3b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('img_url', sa.String(length=240), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'img_url')
    # ### end Alembic commands ###
