"""empty message

Revision ID: f4f1830ea22b
Revises: b5e3ea3739c7
Create Date: 2021-06-17 21:37:03.283508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4f1830ea22b'
down_revision = 'b5e3ea3739c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_constraint('product_categories_id_fkey', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'category', ['category_id'], ['id'])
    op.drop_column('product', 'categories_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('categories_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('product_categories_id_fkey', 'product', 'category', ['categories_id'], ['id'])
    op.drop_column('product', 'category_id')
    # ### end Alembic commands ###
