"""empty message

Revision ID: f599e59038fd
Revises: f4f1830ea22b
Create Date: 2021-06-17 21:49:34.855810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f599e59038fd'
down_revision = 'f4f1830ea22b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_name_key', 'product', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('product_name_key', 'product', ['name'])
    # ### end Alembic commands ###
